#########################
### ACTIVITY CALENDAR ###
#########################

DISPLAY_DATETIME_FORMAT = "%a %B %d, %H:%M %Z"
SHEET_DATETIME_FORMAT = "%m/%d/%y %H:%M %Z"

SHEET_SERVER_COLUMN = 1
SHEET_TIMESTAMP_COLUMN = 2
SHEET_ACTIVITY_COLUMN = 3
SHEET_LINK_COLUMN = 4

UTC = 'UTC'

ACTIVITY_CALENDAR_CHANNEL_ID = 390394020851089408
ACTIVITY_CALENDAR_SHEET_KEY = "11KQuSP8h7O8H-Z9g0ndVIcUD_X-VSWZtz5Iqz-pmBDk"
