#########################
### ACTIVITY CALENDAR ###
#########################

SHEET_SERVER_COLUMN = 1
SHEET_TIMESTAMP_COLUMN = 2
SHEET_ACTIVITY_COLUMN = 3
SHEET_DESCRIPTION_COLUMN = 4
SHEET_LINK_COLUMN = 5

ACTIVITY_CALENDAR_CHANNEL_ID = 390394020851089408
