################
# GOOGLE SHEET #
################

NAME = "Name"
ID = "id"
BALANCE = "Balance"
NUM_BUYINS = "Number of Buyins"
COLUMNS = [NAME, ID, BALANCE, NUM_BUYINS]

##################
##### CASINO #####
##################

OPENING_BALANCE = 500

BLACKJACK = "Blackjack"
BLACKJACK_EMOJI_DISCORD = ":flower_playing_cards:"
SLOTS = "Slots"
SLOTS_EMOJI_DISCORD = ":slot_machine:"
GAMES = [BLACKJACK, SLOTS]
#EMOJIS = [BLACKJACK_EMOJI_DISCORD, SLOTS_EMOJI_DISCORD]
EMOJIS = [SLOTS_EMOJI_DISCORD]

###############
### SLOTS #####
###############

WATERMELON = ":watermelon:"
BANANA = ":banana:"
COIN = ":coin:"
SEVEN = ":seven:"
CHERRIES = ":cherries:"
MONEY = ":money_with_wings:"
CHEESE = ":cheese:"

REELS = [[COIN, CHEESE, MONEY, BANANA, WATERMELON, COIN, BANANA, COIN, SEVEN, WATERMELON, BANANA,
            COIN, MONEY, CHERRIES, WATERMELON, BANANA, COIN, SEVEN, BANANA, WATERMELON],
        [BANANA, CHERRIES, MONEY, CHEESE, COIN, BANANA, CHERRIES, CHERRIES, SEVEN, COIN, BANANA,
         CHERRIES, WATERMELON, CHERRIES, COIN, BANANA, CHERRIES, WATERMELON, MONEY, COIN],
        [CHERRIES, BANANA, MONEY, CHEESE, COIN, CHERRIES, BANANA, WATERMELON, MONEY, COIN,
         CHERRIES, BANANA, WATERMELON, SEVEN, COIN, CHERRIES, BANANA, WATERMELON, CHERRIES, COIN]]
